name: nanodecon
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bcftools=1.9
  - biopython=1.68
  - blas=1.1
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2018.8.24
  - curl=7.64.0
  - deprecated=1.2.13
  - freetype=2.12.1
  - htslib=1.9
  - jpeg=9e
  - kma=1.4.3
  - krb5=1.16.3
  - libcurl=7.64.0
  - libcxx=14.0.6
  - libdeflate=1.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgfortran
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libssh2=1.8.0
  - libtiff=4.2.0
  - libwebp-base=1.2.4
  - libzlib=1.2.13
  - llvm-openmp=14.0.4
  - mmtf-python=1.0.2
  - msgpack-python=0.5.6
  - nanofilt=2.8.0
  - nanoget=1.18.1
  - nanomath=1.2.1
  - ncurses=6.1
  - numpy=1.11.3
  - olefile=0.46
  - openblas=0.3.21
  - openssl=1.0.2u
  - pandas=0.23.4
  - pillow=5.3.0
  - pip=20.3.4
  - pysam=0.15.2
  - python=3.5.5
  - python-dateutil=2.8.1
  - pytz=2022.2
  - readline=7.0
  - reportlab=3.5.8
  - samtools=1.9
  - setuptools=40.4.3
  - six=1.16.0
  - sqlite=3.28.0
  - tk=8.6.12
  - wheel=0.37.1
  - wrapt=1.10.11
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2